<a href="https://colab.research.google.com/github/21it142/Full-Stack-Web-Development-/blob/main/21it142_lab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
numpy_array_1 = np.random.rand(5, 5)
numpy_array_2 = np.eye(5)
print("numpy_array_1")
print(numpy_array_1)
print("numpy_array_2")
print(numpy_array_2)

numpy_array_result = numpy_array_1 + numpy_array_2
np.fill_diagonal(numpy_array_result, 0)
sum = np.sum(numpy_array_result[0, :])
print("numpy_array_result:")
print(numpy_array_result)
print("\nSum:", sum)

numpy_array_1
[[0.05539638 0.51249221 0.38891982 0.35544936 0.44929384]
 [0.57028571 0.50436413 0.26249643 0.28010012 0.5625162 ]
 [0.3117593  0.30122291 0.31776632 0.20876159 0.51347889]
 [0.17382457 0.69660979 0.0946772  0.80013197 0.85518475]
 [0.56493043 0.1656083  0.96340534 0.83285388 0.81525656]]
numpy_array_2
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
numpy_array_result:
[[0.         0.51249221 0.38891982 0.35544936 0.44929384]
 [0.57028571 0.         0.26249643 0.28010012 0.5625162 ]
 [0.3117593  0.30122291 0.         0.20876159 0.51347889]
 [0.17382457 0.69660979 0.0946772  0.         0.85518475]
 [0.56493043 0.1656083  0.96340534 0.83285388 0.        ]]

Sum: 1.7061552278587957


In [17]:
class tax:
    def __init__(self, basic_salary, medical_allowance, travelling_allowance):
        self.basic_salary = basic_salary
        self.medical_allowance = medical_allowance
        self.travelling_allowance = travelling_allowance
        self.tax_deduction = self.calculate_tax()

    def calculate_tax(self):
        income = self.basic_salary + self.medical_allowance + self.travelling_allowance
        if income <= 250:
            return 0
        elif 251 <= income <= 500:
            return 0.1 * income
        elif 501 <= income <= 1000:
            return 0.15 * income
        else:
            return 0.15 * 1000

    def get_total_salary(self):
        return self.basic_salary + self.medical_allowance + self.travelling_allowance

    def get_onhand_salary(self):
        total_salary = self.get_total_salary()
        onhand_salary = total_salary - self.tax_deduction
        return onhand_salary


basic_salary = 200
medical_allowance = 100
travelling_allowance = 50

jay_tax = tax(basic_salary, medical_allowance, travelling_allowance)

print("Total Salary:", jay_tax.get_total_salary())
print("Onhand Salary:", jay_tax.get_onhand_salary())


Total Salary: 350
Onhand Salary: 315.0
